SPLIT_KEYBOARD = yes
SPLIT_TRANSACTIONS = yes
DEFS += -DSPLIT_TRANSACTION_RPC

TRI_LAYER_ENABLE = yes

# OPENRGB_ENABLE = yes
RGB_MATRIX_ENABLE = yes
# RGB_MATRIX_CUSTOM_USER = yes

# RGBLIGHT_ENABLE = yes

# VIA_ENABLE = yes

MOUSEKEY_ENABLE = yes

RAW_ENABLE = yes

DEBUG_ENABLE = yes

# SPLIT_TRANSACTIONS = yes

# AUTOCORRECT_ENABLE = yes
